services:
  db:
    image: mariadb:11.8.5-ubi
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: appUser
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb-pwd
      MARIADB_DATABASE: vehicles_db
    secrets: 
      - mariadb-pwd
    volumes: 
      - db_data:/var/lib/mysql 
      - ./db/dbsetup.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u appUser -p\"$(cat /run/secrets/mariadb-pwd)\"" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USERNAME: appUser
      DB_PASSWORD_FILE: /run/secrets/mariadb-pwd
      DB_HOST: db
      APP_PORT: 3000
    secrets: 
      - mariadb-pwd
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 80:3000

secrets:
  mariadb-pwd:
    file: db_password.txt

volumes:
  db_data: